"""Optional property-based tests for the proof-term core.

This module is skipped entirely if Hypothesis is not installed.
Install with:
    pip install -r requirements-dev.txt

Then run:
    python -m pytest tests/test_proof_term_properties.py -v

The properties tested here correspond to the metatheoretic claims in
docs/metatheory.md.  These tests do NOT formally prove those claims;
they provide evidence by checking them on generated inputs.

Generator design
----------------
Terms are generated by type-directed construction: given a target type T
and a context, we build a term of type T by applying introduction rules.
This guarantees every generated term is well-typed by construction, so
there is no rejection overhead from assumption failures.

Base context: {"a": A, "b": B, "c": C}
Formula atoms: A, B, C (no bottom, to ensure every type is inhabitable)
"""
import pytest

# Skip the entire module if Hypothesis is not available.
# This must be at module level so collection skips cleanly.
pytest.importorskip("hypothesis")

from hypothesis import given, settings, assume, HealthCheck
from hypothesis import strategies as st

from stele.ast import Var as FVar, Op
from stele.core.terms import TVar, Lam, App, Pair, Fst, Snd, Inl, Inr, Case, Abort
from stele.core.typing import infer, check, TypingError, normalize_neg, extend
from stele.core.reduce import (
    free_vars, substitute, step, normalize, is_normal, ReductionError,
)


# ---------------------------------------------------------------------------
# Formula helpers
# ---------------------------------------------------------------------------

def A(): return FVar("A")
def B(): return FVar("B")
def C(): return FVar("C")
def bot(): return Op("bot", ())

_ATOMS = [FVar("A"), FVar("B"), FVar("C")]

# Base context: one variable per atom type; ensures any atom type is inhabitable
_BASE_CTX = {"a": FVar("A"), "b": FVar("B"), "c": FVar("C")}

# Fresh variable name pool for binders (does not collide with a/b/c)
_FRESH_NAMES = ["x", "y", "z", "w", "u", "v", "p", "q"]


# ---------------------------------------------------------------------------
# Formula strategy
# ---------------------------------------------------------------------------

@st.composite
def small_formula(draw, max_depth=2):
    """Generate a small propositional formula with atoms A, B, C (no bottom).

    Excludes bottom so that every generated type is inhabitable with _BASE_CTX.
    """
    if max_depth == 0 or draw(st.booleans()):
        return draw(st.sampled_from(_ATOMS))
    sym = draw(st.sampled_from(["imp", "and", "or"]))
    left  = draw(small_formula(max_depth - 1))
    right = draw(small_formula(max_depth - 1))
    return Op(sym, (left, right))


# ---------------------------------------------------------------------------
# Type-directed term generator
# ---------------------------------------------------------------------------

def _build_term(draw, ctx, ty, depth):
    """Build a term of type ty in ctx by structural induction on ty.

    Guaranteed to produce a well-typed term for any ty built from A/B/C
    and the connectives imp/and/or, given that ctx contains _BASE_CTX.

    Parameters
    ----------
    draw      : Hypothesis draw function (must be called from a @composite)
    ctx       : dict[str, Formula]  (typing context)
    ty        : Formula             (target type)
    depth     : int                 (remaining depth budget)
    """
    nty = normalize_neg(ty)

    # Variables in ctx whose (normalized) type matches nty
    matches = sorted(v for v, vty in ctx.items() if normalize_neg(vty) == nty)

    # At depth 0 or by coin flip: use a matching variable if available
    use_var = depth <= 0 or (bool(matches) and draw(st.booleans()))
    if use_var and matches:
        return TVar(draw(st.sampled_from(matches)))

    # Build by introduction rule
    if isinstance(nty, Op) and nty.sym == "imp":
        A_part, B_part = nty.args
        taken = set(ctx)
        var = next((n for n in _FRESH_NAMES if n not in taken), f"v{len(ctx)}")
        body = _build_term(draw, {**ctx, var: A_part}, B_part, max(0, depth - 1))
        return Lam(var, A_part, body)

    if isinstance(nty, Op) and nty.sym == "and":
        A_part, B_part = nty.args
        left  = _build_term(draw, ctx, A_part, max(0, depth - 1))
        right = _build_term(draw, ctx, B_part, max(0, depth - 1))
        return Pair(left, right)

    if isinstance(nty, Op) and nty.sym == "or":
        A_part, B_part = nty.args
        if draw(st.booleans()):
            return Inl(_build_term(draw, ctx, A_part, max(0, depth - 1)), B_part)
        else:
            return Inr(_build_term(draw, ctx, B_part, max(0, depth - 1)), A_part)

    # Atomic type or bot: must use a variable
    if matches:
        return TVar(draw(st.sampled_from(matches)))

    # Should not reach here with _BASE_CTX and non-bottom atoms
    assume(False)
    return TVar("a")  # unreachable


@st.composite
def well_typed_triple(draw, max_depth=3):
    """Generate (ctx, term, type) where ctx ⊢ term : type by construction."""
    ty   = draw(small_formula(max_depth=2))
    term = _build_term(draw, _BASE_CTX, ty, max_depth)
    return (_BASE_CTX, term, ty)


@st.composite
def well_typed_triple_with_redex(draw, max_depth=3):
    """Generate (ctx, term, type) where term has a beta redex at the top level.

    Used for subject-reduction and substitution-lemma tests.
    The generated term is well-typed by construction and step(term) is not None.
    """
    ty = draw(small_formula(max_depth=2))
    kind = draw(st.sampled_from(["imp", "fst", "snd", "case_l", "case_r"]))

    if kind == "imp":
        # App(Lam(x, A, body), arg) : ty
        A_part = draw(small_formula(max_depth=1))
        var = "x"
        body = _build_term(draw, {**_BASE_CTX, var: A_part}, ty, max_depth - 1)
        arg  = _build_term(draw, _BASE_CTX, A_part, max_depth - 1)
        term = App(Lam(var, A_part, body), arg)

    elif kind == "fst":
        # Fst(Pair(left, right)) : ty
        B_part = draw(small_formula(max_depth=1))
        left  = _build_term(draw, _BASE_CTX, ty,     max_depth - 1)
        right = _build_term(draw, _BASE_CTX, B_part, max_depth - 1)
        term  = Fst(Pair(left, right))

    elif kind == "snd":
        # Snd(Pair(left, right)) : ty
        A_part = draw(small_formula(max_depth=1))
        left  = _build_term(draw, _BASE_CTX, A_part, max_depth - 1)
        right = _build_term(draw, _BASE_CTX, ty,     max_depth - 1)
        term  = Snd(Pair(left, right))

    elif kind == "case_l":
        # Case(Inl(val, B), x, lb, y, rb) : ty
        A_part = draw(small_formula(max_depth=1))
        B_part = draw(small_formula(max_depth=1))
        val = _build_term(draw, _BASE_CTX, A_part, max_depth - 1)
        lb  = _build_term(draw, {**_BASE_CTX, "x": A_part}, ty, max_depth - 1)
        rb  = _build_term(draw, {**_BASE_CTX, "y": B_part}, ty, max_depth - 1)
        term = Case(Inl(val, B_part), "x", lb, "y", rb)

    else:  # case_r
        # Case(Inr(val, A), x, lb, y, rb) : ty
        A_part = draw(small_formula(max_depth=1))
        B_part = draw(small_formula(max_depth=1))
        val = _build_term(draw, _BASE_CTX, B_part, max_depth - 1)
        lb  = _build_term(draw, {**_BASE_CTX, "x": A_part}, ty, max_depth - 1)
        rb  = _build_term(draw, {**_BASE_CTX, "y": B_part}, ty, max_depth - 1)
        term = Case(Inr(val, A_part), "x", lb, "y", rb)

    return (_BASE_CTX, term, ty)


@st.composite
def subst_data(draw, max_depth=3):
    """Generate (ctx, body, arg, var, A, B) such that:
       ctx + {var: A} ⊢ body : B
       ctx            ⊢ arg  : A
    """
    A_part = draw(small_formula(max_depth=1))
    B_part = draw(small_formula(max_depth=2))
    var    = "subst_x"
    inner_ctx = {**_BASE_CTX, var: A_part}
    body = _build_term(draw, inner_ctx, B_part, max_depth)
    arg  = _build_term(draw, _BASE_CTX,  A_part, max_depth)
    return (_BASE_CTX, body, arg, var, A_part, B_part)


# ---------------------------------------------------------------------------
# Shared settings
# ---------------------------------------------------------------------------

_SETTINGS = settings(
    max_examples=50,
    deadline=None,   # normalization may be slow for larger terms
    suppress_health_check=[HealthCheck.too_slow],
)


# ---------------------------------------------------------------------------
# Property 1: Type-directed generator produces well-typed terms
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple())
def test_generated_terms_typecheck(triple):
    """Type-directed generator always produces well-typed terms.

    Corresponds to: generator correctness (not a metatheorem).
    If this test fails, the generator itself is broken.
    """
    ctx, term, ty = triple
    try:
        inferred = infer(ctx, term)
    except TypingError as e:
        pytest.fail(f"Generator produced ill-typed term: {e}\nterm={term}\ntype={ty}")
    assert normalize_neg(inferred) == normalize_neg(ty), (
        f"Inferred type {inferred} != expected {ty}\nterm={term}"
    )


# ---------------------------------------------------------------------------
# Property 2: Subject reduction — type is preserved under step
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple_with_redex())
def test_subject_reduction_property(triple):
    """If Γ ⊢ t : A and step(t) = t', then Γ ⊢ t' : A.

    Corresponds to: Claim 2 (Subject Reduction) in docs/metatheory.md.
    """
    ctx, term, ty = triple

    stepped = step(term)
    assert stepped is not None, (
        "well_typed_triple_with_redex should always generate a reducible term"
    )

    try:
        inferred_after = infer(ctx, stepped)
    except TypingError as e:
        pytest.fail(
            f"Subject reduction violated: stepped term ill-typed: {e}\n"
            f"before={term}\nafter={stepped}\ntype={ty}"
        )

    assert normalize_neg(inferred_after) == normalize_neg(ty), (
        f"Subject reduction violated: type changed\n"
        f"before type: {ty}\nafter type: {inferred_after}\n"
        f"before={term}\nafter={stepped}"
    )


# ---------------------------------------------------------------------------
# Property 3: Normalization preserves type
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple())
def test_normalization_preserves_type(triple):
    """If Γ ⊢ t : A then Γ ⊢ normalize(t) : A.

    Corresponds to: Claim 3 (Normalization) in docs/metatheory.md.
    """
    ctx, term, ty = triple

    try:
        normal = normalize(term)
    except ReductionError as e:
        pytest.fail(f"ReductionError during normalization: {e}\nterm={term}")

    try:
        inferred = infer(ctx, normal)
    except TypingError as e:
        pytest.fail(
            f"Normal form is ill-typed: {e}\n"
            f"original={term}\nnormal={normal}\ntype={ty}"
        )

    assert normalize_neg(inferred) == normalize_neg(ty), (
        f"Normalization changed type: {ty} -> {inferred}\n"
        f"original={term}\nnormal={normal}"
    )


# ---------------------------------------------------------------------------
# Property 4: Normalization reaches a normal form
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple())
def test_normalization_reaches_normal_form(triple):
    """is_normal(normalize(t)) is True for well-typed terms.

    Corresponds to: Claim 3 (Normalization) in docs/metatheory.md.
    """
    _, term, _ = triple

    try:
        normal = normalize(term)
    except ReductionError as e:
        pytest.fail(f"ReductionError during normalization: {e}\nterm={term}")

    assert is_normal(normal), (
        f"normalize(t) is not in normal form\n"
        f"original={term}\nnormal={normal}\n"
        f"next step={step(normal)}"
    )


# ---------------------------------------------------------------------------
# Property 5: Idempotence of normalization
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple())
def test_idempotence_of_normalization(triple):
    """normalize(normalize(t)) == normalize(t).

    Corresponds to: Claim 3 (Normalization) — already-normal terms are fixed points.
    """
    _, term, _ = triple

    try:
        n1 = normalize(term)
        n2 = normalize(n1)
    except ReductionError as e:
        pytest.fail(f"ReductionError: {e}\nterm={term}")

    assert n1 == n2, (
        f"Normalization is not idempotent\n"
        f"normalize(t)       = {n1}\n"
        f"normalize(n(t))    = {n2}"
    )


# ---------------------------------------------------------------------------
# Property 6: Substitution lemma
# ---------------------------------------------------------------------------

@_SETTINGS
@given(subst_data())
def test_substitution_lemma(data):
    """If Γ, x:A ⊢ body : B and Γ ⊢ arg : A, then Γ ⊢ body[arg/x] : B.

    This is the substitution lemma, a key step in proving subject reduction.
    Corresponds to: Claim 2 (Subject Reduction) in docs/metatheory.md.
    """
    ctx, body, arg, var, A_part, B_part = data

    substituted = substitute(body, var, arg)

    try:
        inferred = infer(ctx, substituted)
    except TypingError as e:
        pytest.fail(
            f"Substitution lemma violated: {e}\n"
            f"body={body}\narg={arg}\nvar={var}\nA={A_part}\nB={B_part}"
        )

    assert normalize_neg(inferred) == normalize_neg(B_part), (
        f"Substitution lemma: wrong type after subst\n"
        f"expected={B_part}\ngot={inferred}\n"
        f"body={body}\narg={arg}"
    )


# ---------------------------------------------------------------------------
# Property 7: No closed false term from introduction rules
# ---------------------------------------------------------------------------

@_SETTINGS
@given(well_typed_triple())
def test_no_closed_false_from_intro_rules(triple):
    """Well-typed terms generated by introduction rules do not have type false.

    Corresponds to: Claim 5 (Core Consistency) in docs/metatheory.md.
    This is a sampling-based test, not a proof of consistency.
    """
    ctx, term, ty = triple
    false_ty = normalize_neg(bot())

    # The target type we requested was ty (from small_formula, no bot)
    # Verify that inferred type is not false
    inferred = infer(ctx, term)
    assert normalize_neg(inferred) != false_ty, (
        f"Generated term has type false\nterm={term}\ntype={inferred}"
    )

    # Also check the normal form
    try:
        normal = normalize(term)
    except ReductionError:
        return  # unexpected, but not a consistency violation

    inferred_normal = infer(ctx, normal)
    assert normalize_neg(inferred_normal) != false_ty, (
        f"Normal form has type false\nnormal={normal}\ntype={inferred_normal}"
    )
